### ISSUE TITLE
RegionChart引用了不存在的chart/util

### ISSUE THREAD

**Issue by otakustay** [ecomfe/ub-ria-ui#142]
使用了`formatNumber`方法，需处理  @xutingting02 这个能尽快不？

**Comment by xutingting02** [comment]
之前是把chart里面的util合并到了helper/util，regionChart控件引用的是helper/util，你是不是没更新最新代码？

**Comment by otakustay** [comment]
我用的是edp的最新版本，需要我再把ub-ria-ui发个新版本吗？

xutingting <notifications@github.com>于2016年7月4日 周一下午5:45写道：

**Comment by yankun01** [comment]
@otakustay 现在是beta.3，再发个吧。

**Comment by otakustay** [comment]
ok

yankun01 <notifications@github.com>于2016年7月4日 周一下午6:59写道：
