### ISSUE TITLE
[输入框]下拉输入框

### ISSUE THREAD

**Issue by otakustay** [ecomfe/ub-ria-ui#15]
有2种可能的需求要明确：

1. 输入框用于搜索下拉框的内容，最终还是只能从下拉框点
2. 输入框可自由输入，下拉框只是一种辅助

![80027276086c7df254fc2f4bdf4c7acd](https://cloud.githubusercontent.com/assets/639549/4246153/f8b20f80-3a45-11e4-85f7-9918b610d851.jpeg)

@Exodia

**Comment by yankun01** [comment]
已经实现了。
